authors:
  ABBAPOH:
    name: Ivan Komissarov
    description: Contributor
    avatar: https://github.com/ABBAPOH.png
  ckandeler:
    name: Christian Kandeler
    description: Maintainer
    avatar: https://github.com/ckandeler.png
  rweickelt:
    name: Richard Weickelt
    description: Contributor
    avatar: https://github.com/rweickelt.png
